name: balancinggroups
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch 
  - torchvision 
  - cudatoolkit=10.2
  - pip:
    - gdown>=4.2.0
    - matplotlib>=3.4.3
    - numpy>=1.19.5
    - pandas>=1.3.3
    - Pillow>=8.4.0
    - scikit-learn>=1.0.1
    - scipy>=1.7.1
    - seaborn>=0.11.2
    - submitit>=1.3.3
    - tqdm>=4.62.2
    - transformers>=4.10.0
